language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

# debian packages
addons:
   apt:
      packages:
      - haskell-platform

# command to install dependencies
install: "pip install ply Jinja2"

# command to run tests
script: make test

sudo: false
